# image: ruby:2.2

# services:
#   - mongo

before_script:
  - gem install bundler
  - bundle install
  - cp config/mongoid.yml.tmpl config/mongoid.yml
  - bower install

stages:
  - test

unit_test:
  stage: test
  script:
    - bundle exec rake test:units

acceptance_test:
  stage: test
  script:
    - bundle exec rake test:features