# image: ruby:2.2

# services:
#   - mongo

before_script:
  - gem install bundler
  - bundle install
  - cp config/mongoid.yml.tmpl config/mongoid.yml
  - bower install

minitest:
  script:
    - bundle exec rake test